name: Android rom application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: wuxianlin/android_rom_tools

    - uses: actions/checkout@v2
      with:
        path: main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install dependencies
      run: |
        sudo apt-get install axel brotli
        ./setup.sh ${{ secrets.GITHUB_TOKEN }}

    - name: Run
      run: |
        bash main/test.sh

