name: Android rom application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        path: tools
        repository: wuxianlin/android_rom_tools

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install axel brotli maven
        ./tools/setup.sh ${{ secrets.GITHUB_TOKEN }}
        python -m pip install --upgrade pip
        if [ -f tools/requirements.txt ]; then pip install -r tools/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies for Mariana Trench
      run: |
        brew install cmake zlib boost jsoncpp fmt re2 git
        brew install googletest --build-from-source
        sudo apt update
        sudo apt install default-jre default-jdk

    - name: Install Redex and build Mariana Trench
      run: |
        git clone --depth 1 https://github.com/facebook/mariana-trench
        cd mariana-trench
        git apply ../patches/mariana-trench.diff
        export CMAKE_PREFIX_PATH=/home/linuxbrew/.linuxbrew/opt/jsoncpp:/home/linuxbrew/.linuxbrew/opt/zlib
        git clone --depth 1 https://github.com/facebook/redex
        cd redex
        git apply ../../patches/redex.diff
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX="../install" ..
        make -j$(nproc)
        make install
        cd ../..
        mkdir build
        cd build
        cmake -DREDEX_ROOT="../redex/install" -DCMAKE_INSTALL_PREFIX="../install" ..
        make -j$(nproc)
        make install

    - name: Run
      run: |
        bash test-mariana-trench.sh

    - uses: actions/upload-artifact@v2
      with:
        name: result
        path:  test/

