name: Android rom application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: wuxianlin/android_rom_tools

    - uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout FlowDroid
      uses: actions/checkout@v2
      with:
        repository: secure-software-engineering/FlowDroid
        ref: develop
        path: FlowDroid

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install axel brotli maven
        ./setup.sh ${{ secrets.GITHUB_TOKEN }}
        python -m pip install --upgrade pip
        if [ -f main/requirements.txt ]; then pip install -r main/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "GitHub Action"
        #cd FlowDroid
        #git apply --check ../main/0001-fix-flowdroid-develop-version-build.patch && git am ../main/0001-fix-flowdroid-develop-version-build.patch
        #mvn -DskipTests install

    - name: Run
      run: |
        bash main/test-jadx.sh

    - uses: actions/upload-artifact@v2
      with:
        name: decompiled-jadx
        path: out/rom-decompiled-jadx/

